### ISSUE TITLE
Please search the "license_key="

### ISSUE THREAD

**Issue by bagushp** [samleong123/heroku-clearkey-hex-base64-json#1]
Helo Mr Sam,
Please search the "#KODIPROP:inputstream.adaptive.license_key="
from ?

https://unifi-live01.secureswiftcontent.com/UnifiHD/live06.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live07.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live08.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live09.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live11.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live12.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live13.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live14.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live15.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live16.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live17.mpd
https://unifi-live01.secureswiftcontent.com/UnifiHD/live18.mpd

Thankyou

**Comment by samleong123** [comment]
Unrelated issue
